python3 stereo_resumable_dist_trainer.py --name great-igevsolid-stereo \
--logdir ./experiments/great_stereo/solid/igev-based/kitti/baseline \
--restore_ckpt ./great-igevsolid-stereo.pth \
--optimizer adamw \
--batch_size 8 \
--seed 655 \
--train_datasets kitti \
--train_datasets_root ~/Workspaces/Researches/Datasets/KITTI \
--lr 0.0001 \
--num_steps 50000 \
--image_size 320 736 \
--train_iters 22 \
--wdecay 0.00001 \
--eval_iters 32 \
--cv_levels 2 \
--cv_radius 4 \
--n_downsample 2 \
--n_gru_layers 3 \
--channels 128 128 128 \
--context_norm batch \
--max_disp 192 \
--spatial_scale -0.2 0.5 \
--saturation_range 0.7 1.3 \
--precision_dtype bfloat16 \
--noyjitter \
--mixed_precision
